version: '3.7'

services:
  raffle_person:
    build: .
    container_name: raffle_container
    restart: always
    volumes:
      - ./:/code/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      - DATABASE_HOST=postgres_db
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - 5439:${DATABASE_PORT}

volumes:
  postgres_data: